/*
 * To change this license header,
choose License Headers in Project Properties.
 * To change this template file,
choose Tools | Templates
 * and open the template in the editor.
 */
package Client.skills;

/**
 * 技能信息(該信息和技能屬性有關)
 *
 * @author setosan
 */
public enum SkillInfo {
    damagetoUndead,
    landingEffect,
    invincible,
    invisible,
    commandSkillType,
    type,
    mpDrain,
    ignoreImmune,
    rapidAttack,
    piercingPenalty,
    addDamInHiding,
    deadlyAttack,
    summonMinion,
    showFromTheHead,
    energyCharge,
    pvp,
    mesoDrop,
    switchDamtoMeso,
    delay,
    debuff,
    morph,
    ignoreCounter,
    incDamToDarknessTarget,
    incDamToFreezeTarget,
    MADReflect,
    switchDamtoMP,
    showFromTheOrigin,
    dot,
    hpDrain,
    itemSteal,
    mesoExplosion,
    magicSteal,
    nextAttackisCritical,
    elemAttr,
    requireHighestJump,
    selfDestructMinion,
    prop,
    keydownThrowing,
    specialNormalAttack,
    runeSkill,
    pullTarget,
    chainAttack,
    lastSummonTrigger,
    specialGage,
    dispel,
    knockbackLimit,
    massSpell,
    fullChargeEffect,
    minionAttack,
    smartKnockBack,
    affectedSkill,
    mpSteal,
    dmgDelay,
    zoneType,
    casterMove,
    specialAttackFinish,
    dropItemID,
    blessingArmor,
    bodyAttack,
    multiTargeting,
    vehicleAttackSkill,
    movingAttack,
    avaliableInJumpingState,
    continuousAreaAttack,
    pushTarget,
    condition,
    chainattackPenalty,
    incDam,
    peicing,
    passCounter,
    dotType,
    PADReflect,
    affectedSkillEffect,
    finalAttack,
    autoHiding,
    piercing,
    trembling,
    magicDamage,
    reqLevel,
    ignoreTargetPDP,
    openGate,
    areaAttack,
    weapon,
    mes,
    mesToBoss,
    mesEnableBossTime,
    suddenDeath,
    value,
    rangeAttack,
    requireSkill,
    counter,
    chargingSkill,
    incDamToStunTarget,
    upperAttack,
    cannotCancelByRButton,
    ironBody,
    periodicAttackCount,
    minionAbility,
    splash,
    rectBasedOnTarget,
    piercingBouns,
    skillOrigin, // V.149 new 152101000 古代水晶
    attackAfter, // 80003047
    rushToPoint,
    MainSkillID_WZ2,
    excl,
    collabo // V264.1 ADD+
}
