package Config.constants.enums;

public enum SecurityCheckType {
    SECURITYPACKET_MEMORY_CHECK(0x0),
    SECURITYPACKET_FULL_MEMORY_CHECK(0x1),
    SECURITYPACKET_CHECK_CLIENT_INTEGRITY(0x2),
    SECURITYPACKET_CHECK_CLIENT_UPDATE_INTERVAL(0x3),
    SECURITYPACKET_CLIENT_VERSION(0x4),
    SECURITYPACKET_LOGPACKET(0x5),
    SECURITYPACKET_NGS_CLIENTTOSERVER(0x6),
    SECURITYPACKET_NGS_SERVERTOCLIENT(0x7),
    SECURITYPACKET_NGS_CRASHCLIENT(0x8),
    SECURITYPACKET_NGS_MIDBLOCKCRASHCLIENT(0x9),
    SECURITYPACKET_HSHIELD_CRASHCLIENT(0xA),
    SECURITYPACKET_AUTH_HSHIELD(0xB),
    SECURITYPACKET_REQUESTCHECKCLIENTINTEGRITY(0xC),
    SECURITYPACKET_XIGNCODE_CLIENTTOSERVER(0xD),
    SECURITYPACKET_XIGNCODE_SERVERTOCLIENT(0xE);

    public final byte value;

    SecurityCheckType(final int value) {
        this.value = (byte) value;
    }
}
